#
# cross build for fsck
#
# cmd/fsck/GNUmakefile
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= fsck
CLASS	= cmd
LIBS	= $(DEPTH)/lib/fslib/libfs.a

include $(DEPTH)/GNUmakefile.inc
