#
# cross build for who
#
# cmd/who/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into who.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= who
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
