#
# Makefile for updating the source tree
#
# cmd/echo/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../..
DIR = echo
CLASS = cmd

SRCS = $(wildcard *.c *.h)

include $(DEPTH)/GNUmakefile.inc
