#
# cross build for echo
#
# cmd/echo/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into echo.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= echo
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
