#
# Makefile for updating the source tree
#
# cmd/whitesmith/lib/libm/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../../..
DIR = libm
CLASS = cmd/whitesmith/lib

SRCS = $(wildcard *.s *.c)

include $(DEPTH)/GNUmakefile.inc
