#
# cross build for date
#
# cmd/date/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into date.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= date
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
