/* generated by makeerror.awk from errorcodes */
#ifdef DEF_ERRMSG
char *errmsg[] = {
	"bad type decl",
	"bad typedef",
	"bad enum",
	"bad enum tag",
	"dup aggregate",
	"no basetype",
	"struct too big",
	"union bitfield",
	"bad struct elem",
	"no struct def",
	"multi basetype",
	"dup type def",
	"bad type ref",
	"unknown type",
	"decl parens",
	"multi vars",
	"bitfield dim",
	"bitfield big",
	"array dim",
	"fn array",
	"old style arg",
	"multi arg type",
	"bad decl token",
	"bad sclass",
	"too many names",
	"dup name",
	"bad init",
	"auto aggr init",
	"redecl disagrees",
	"sizeof indeterminate",
	"union init",
	"bad sclass",
	"need }",
	"cond parens",
	"need ;",
	"orphan else",
	"case not const",
	"label :",
	"bad do",
	"need while",
	"goto label",
	"switch {",
	"bad stmt",
	"bad cpp op",
	"endif no if",
	"multi else",
	"no macro name",
	"bad include",
	"no include",
	"bad macro args",
	"cpp const",
	"bad literal",
	"bad char",
	"char range",
	"bad number",
	"bad char",
	"id too long",
	"need lvalue",
	"bad deref",
	"scalar op",
	"cast paren",
	"expr paren",
	"bad index",
	"need ]",
	"need fn ptr",
	"bad fn args",
	"bad op",
	"undefined symbol",
	"no fold",
	"ptr compat",
	"struct value",
	"addr of register",
	"out of memory",
	"sym truncated",
	"too many ifs",
	"locals too large",
	"too many functions",
	"too many blocks",
	"incomplete type",
	"unknown error"
};
#else
/*
 * Numbers, not an enum.  cpp interns every identifier it
 * lexes, and an enum puts all seventy-odd of these in the
 * pool of every source that includes this - 1935 bytes of
 * cpp heap, in sources that name at most nine of them.  A
 * define is substituted at the point of use and the rest
 * cost a compact numeric entry apiece.
 *
 * The values are the enum's, counted here rather than by
 * the compiler, which is the whole reason this file is
 * generated: nothing has to be renumbered by hand.
 */
#define ER_T_PT 1
#define ER_T_TD 2
#define ER_T_ED 3
#define ER_T_ET 4
#define ER_T_SA 5
#define ER_T_GB 6
#define ER_T_SB 7
#define ER_T_UB 8
#define ER_T_SE 9
#define ER_T_SD 10
#define ER_T_DT 11
#define ER_T_RT 12
#define ER_T_PA 13
#define ER_T_UT 14
#define ER_D_DP 15
#define ER_D_MV 16
#define ER_D_BD 17
#define ER_D_BM 18
#define ER_D_AD 19
#define ER_D_FA 20
#define ER_D_FM 21
#define ER_D_FO 22
#define ER_D_UT 23
#define ER_D_TL 24
#define ER_D_OF 25
#define ER_D_DN 26
#define ER_D_IN 27
#define ER_D_AI 28
#define ER_D_RD 29
#define ER_D_IA 30
#define ER_D_UI 31
#define ER_P_SC 32
#define ER_S_CC 33
#define ER_S_NP 34
#define ER_S_SN 35
#define ER_S_OE 36
#define ER_S_NC 37
#define ER_S_NL 38
#define ER_S_DO 39
#define ER_S_WH 40
#define ER_S_GL 41
#define ER_S_SB 42
#define ER_S_UK 43
#define ER_C_BD 44
#define ER_C_CU 45
#define ER_C_ME 46
#define ER_C_MN 47
#define ER_C_ID 48
#define ER_C_IF 49
#define ER_C_DP 50
#define ER_C_CE 51
#define ER_C_CD 52
#define ER_C_BC 53
#define ER_C_NR 54
#define ER_C_NX 55
#define ER_C_UT 56
#define ER_C_TL 57
#define ER_E_LV 58
#define ER_E_DP 59
#define ER_E_SC 60
#define ER_E_CP 61
#define ER_E_SP 62
#define ER_E_IT 63
#define ER_E_IB 64
#define ER_E_FN 65
#define ER_E_FA 66
#define ER_E_UO 67
#define ER_E_UD 68
#define ER_E_CF 69
#define ER_E_PT 70
#define ER_E_AG 71
#define ER_E_RA 72
#define ER_NOMEM 73
#define ER_W_SYMTRUNC 74
#define ER_S_IF 75
#define ER_D_FL 76
#define ER_S_FN 77
#define ER_S_BLK 78
#define ER_E_IC 79
#define ER_WTF 80
typedef int error_t;
#endif
