BEGIN { 
	print "/* generated by makeerror.awk from errorcodes */";
	print "#ifdef DEF_ERRMSG"
	print "char *errmsg[] = {"; 
}
/^ER/ {
	code = $1;
	codes[ci++] = code;
	e = substr($0, length(code)+1); 
	sub("[ \t]*","",e);
	printf("\t\"%s\",\n", e); 
}
END { 
	printf("\t\"%s\"\n", "unknown error");
	print "};"; 
	print "#else";
	print "/*";
	print " * Numbers, not an enum.  cpp interns every identifier it";
	print " * lexes, and an enum puts all seventy-odd of these in the";
	print " * pool of every source that includes this - 1935 bytes of";
	print " * cpp heap, in sources that name at most nine of them.  A";
	print " * define is substituted at the point of use and the rest";
	print " * cost a compact numeric entry apiece.";
	print " *";
	print " * The values are the enum's, counted here rather than by";
	print " * the compiler, which is the whole reason this file is";
	print " * generated: nothing has to be renumbered by hand.";
	print " */";
	for (i = 0; i < ci; i++)
		printf("#define %s %d\n", codes[i], i + 1);
	printf("#define %s %d\n", "ER_WTF", ci + 1);
	print "typedef int error_t;"
	print "#endif";
}
