#
# cross build for label
#
# cmd/label/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into label.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= label
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
