#
# cross build for strings
#
# cmd/strings/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into strings.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= strings
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
