/*
 * program to build a data string for insertion into the
 * version message
 *
 * sys/makedate.c
 * Changed: <2021-12-30 19:05:44 curt>
 */
#include <types.h>
#include <std.h>
#include <time.h>

main()
{
	long clock;
	struct time *tm;
	char buf[1000];
	int fd;
	char *comment = "/* Generated by makedate */\n";

	time(&clock);
	tm = localtime(&clock);
	
	fd = creat("build.h", 0777);
	write(fd, comment, strlen(comment));
	sprintf(buf, "#define	BUILD_DATE \"Created %2d/%2d/%2d\\n\"\n", 
		tm->month + 1, tm->day_month, tm->year + 1900);
	write(fd, buf, strlen(buf));
	close(fd);
	exit(0);
}

