#
# cross build for login
#
# cmd/login/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into login.
#
# login.ctl, login.dist and login.dis are data, not sources, and are not
# shipped by the update rule - the same as init's.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= login
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
