#
# cross build for sync
#
# cmd/sync/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into sync.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= sync
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
