#
# cross build for stty
#
# cmd/stty/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into stty.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= stty
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
