#
# hardware simulator top level makefile
#
# hwsim/Makefile 
#
# Changed: <2023-06-23 00:27:25 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

TARGETS = hwsim.o s100.o
INCLUDE = -I../include

# specific machine directories
DIRS = d1

include ../Makefile.inc


