#
# cross build for od
#
# cmd/od/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into od.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= od
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
