#
# cross build for diff
#
# cmd/diff/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into diff.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= diff
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
