#
# cross build for sum
#
# cmd/sum/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into sum.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= sum
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
