#
# cross build for td
#
# cmd/td/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into td.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= td
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
