#
# cross build for ar
#
# cmd/ar/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into ar.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= ar
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
