#
# cross build for dd
#
# cmd/dd/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into dd.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= dd
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
