#
# cross build for su
#
# cmd/su/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into su.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= su
CLASS	= cmd
#
# Set-user-id root, as the distribution's was: see INSTALLMODE in
# GNUmakefile.inc.
#
MODE	= 4711

include $(DEPTH)/GNUmakefile.inc
