#
# makefile for formatmw
#
# micronix/cmd/cpmtools/Makefile
#
# Changed: <2023-06-23 01:07:31 curt>

all:	formatmw.com

formatmw.com:	formatmw.c
	cc -o formatmw.com formatmw.c -lwsc -cpm

install:

clean:

# vim: tabstop=4 shiftwidth=4 noexpandtab:
