#
# cross build for mwformat
#
# cmd/mwformat/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into mwformat.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= mwformat
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
