#
# cross build for unlz4
#
# cmd/unlz4/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into unlz4.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= unlz4
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
