#
# cross build for group
#
# cmd/group/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into group.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= group
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
