#
# cross build for icheck
#
# cmd/icheck/GNUmakefile
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= icheck
CLASS	= cmd
LIBS	= $(DEPTH)/lib/fslib/libfs.a

include $(DEPTH)/GNUmakefile.inc
