#
# cross build for comm
#
# cmd/comm/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into comm.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= comm
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
