#
# cross build for sort
#
# cmd/sort/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into sort.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= sort
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
