#
# cross build for mail
#
# cmd/mail/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into mail.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= mail
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
