#
# Makefile for building the whitesmith tools
#
# cmd/whitesmith/GNUmakefile
#
# Changed: <2023-07-28 18:50:50 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

CLASS = cmd/
DIR = whitesmith
DEPTH = ../..
DIRS = asm p1 p2 pp util link lib include

include $(DEPTH)/GNUmakefile.inc
