#
# cross build for tar
#
# cmd/tar/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into tar.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= tar
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
