#
# cross build for unique
#
# cmd/unique/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into unique.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= unique
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
