#
# cross build for print
#
# cmd/print/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into print.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= print
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
