#
# Makefile for cross
#
# cmd/whitesmith/lib/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
CLASS = cmd/whitesmith
DIR = lib
DIRS = libws libm libu

include $(DEPTH)/GNUmakefile.inc
