#
# cross build for cc
#
# cmd/cc/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into cc.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= cc
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
