#
# cross Makefile for cc
#
# cmd/cc/GNUmakefile
#
# Changed: <2023-07-27 12:56:25 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../..
DIR = cc
CLASS = cmd

SRCS = $(wildcard *.c *.h)
TARGET = cc

include $(DEPTH)/GNUmakefile.inc

