#
# cross build for expand
#
# cmd/expand/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into expand.
#
# BINDIR IS /usr/bin, NOT THE /bin THE REST OF THE COMMANDS GO IN.  The
# distribution kept these with the text tools - archive, kwic, translit
# and the rest - and the native makefile beside this one agrees.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= expand
CLASS	= cmd
BINDIR	= /usr/bin

include $(DEPTH)/GNUmakefile.inc
