#
# cross build for lz4
#
# cmd/lz4/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into lz4.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= lz4
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
