#
# Makefile for updating the source tree
#
# cmd/whitesmith/pp/GNUmakefile
#
# Changed: <2023-07-27 12:51:22 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = pp
CLASS = cmd/whitesmith
TARGET = pp

DOCSRCS = pp.mp p0lex.ic p0main.ic p0subs.ic
SRCS = $(wildcard *.c *.h) $(DOCSRCS)

include $(DEPTH)/GNUmakefile.inc
