#
# cross build for mv
#
# cmd/mv/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into mv.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= mv
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
