#
# cross build for xargs
#
# cmd/xargs/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into xargs.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= xargs
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
