#
# cross build for du
#
# cmd/du/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into du.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= du
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
