#
# cross build for rmdir
#
# cmd/rmdir/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into rmdir.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= rmdir
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
