#
# cross build for grep
#
# cmd/grep/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into grep.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= grep
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
