#
# cross build for md
#
# cmd/md/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into md.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= md
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
