#
# Makefile to install the include/sys header files
#
# micronix/include/sys/Makefile 
#
# Changed: <2023-06-23 01:01:56 curt>

INCLUDES = \
	access.h buf.h con.h dir.h file.h fs.h inode.h lock.h mount.h \
	proc.h reg.h sgtty.h signal.h stat.h sys.h tty.h dj.h mw.h

all:

install:
	mkdir /include/sys
	cp $(INCLUDES) /include/sys

# vim: tabstop=4 shiftwidth=4 expandtab:
