#
# Makefile for pass 2 of the whitesmith c compiler
#
# cmd/whitesmith/p2/GNUmakefile
#
# Changed: <2023-07-29 13:41:52 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = p2
CLASS = cmd/whitesmith
TARGET = p2

include $(DEPTH)/GNUmakefile.inc
