#
# Makefile for updating the source tree
#
# cmd/whitesmith/p2/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = p2
CLASS = cmd/whitesmith
ROOT = ~/src/micronix/filesystem

SRCS = $(wildcard *.c *.h)

DOCSRCS = p2.mp p2.ic p2expr.ic p2fmov.ic p2gen.ic \
	p2jump.ic p2main.ic p2subs.ic p2tab.ic

include $(DEPTH)/GNUmakefile.inc
