#
# cross build for pwd
#
# cmd/pwd/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into pwd.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= pwd
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
