#
# Makefile for updating the source tree
#
# cmd/whitesmith/pwd/GNUmakefile
#
# Changed: <2023-07-29 11:22:12 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../..
DIR = pwd
CLASS = cmd
ROOT = ~/src/micronix/filesystem
SRCDIR = /usr/src/$(CLASS)/$(DIR)

include $(DEPTH)/GNUmakefile.inc

