#
# Makefile for pass 1 of the whitesmith c compiler
#
# cmd/whitesmith/p1/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = p1
CLASS = cmd/whitesmith

SRCS = $(wildcard *.c *.h)

DOCSRCS = p1.mp p1data.ic p1expr.ic p1func.ic p1gets.ic p1.ic p1main.ic \
	p1puts.ic p1red.ic p1subs.ic p1type.ic

include $(DEPTH)/GNUmakefile.inc
