#
# Makefile for pass 1 of the whitesmith c compiler
#
# cmd/whitesmith/p1/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = p1
CLASS = cmd/whitesmith
TARGET = p1

include $(DEPTH)/GNUmakefile.inc
