#
# cross build for umount
#
# cmd/umount/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into umount.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= umount
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
