#
# cross build for fgrep
#
# cmd/fgrep/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into fgrep.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= fgrep
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
