#
# Makefile for 
#
# <path>
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

all:	bdos.lst ccp.lst cbios-e3.lst

bdos.lst: bdos.asm
	asl -L bdos.asm

ccp.lst: ccp.asm
	asl -L ccp.asm

cbios-e3.lst: cbios-e3.asm
	asl -L cbios-e3.asm
