#
# cross build for sh
#
# cmd/sh/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into sh.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= sh
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
