#
# Makefile for updating the source tree
#
# cmd/sh/GNUmakefile
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../..
DIR = sh
CLASS = cmd

SRCS = $(wildcard *.c *.h)

include $(DEPTH)/GNUmakefile.inc
