#
# cross build for newuser
#
# cmd/newuser/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into newuser.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= newuser
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
