
install : 
	mkdir /old
	cd Make ; make install
	cd cc ; make install
	cd cp ; make install
	cd ls ; make install
	cd pwd ; make install
	cd rm ; make install
	cd vi ; make install
	cd mknod ; make install
	cp/cp reset /bin/reset
	# cd msh ; make install

clean : 
	cd Make ; make clean
	cd cc ; make install
	cd cp ; make clean
	cd ls ; make clean
	cd pwd ; make clean
	cd far ; make clean
	cd rm ; make clean
	cd mknod ; make clean
	cd vi ; make clean
	# cd msh ; make clean
