#
# makefile for cmd
#
# micronix/cmd/Makefile
#
# Changed: <2023-07-10 14:36:31 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

upgrade : 
	cd Make ; make upgrade
	cd cc ; make upgrade
	cd cp ; make upgrade
	cd ls ; make upgrade
	cd pwd ; make upgrade
	cd rm ; make upgrade
	cd mknod ; make upgrade
	cd mkdir ; make upgrade

install : 
	cd Make ; make install
	cd cc ; make install
	cd cp ; make install
	cd ls ; make install
	cd pwd ; make install
	cd rm ; make install
	cd vi ; make install
	cd mknod ; make install
	cd mkdir ; make install
	cp/cp reset /bin/reset
	cd echo ; make echo
	# cd ar ; make install
	# cd far ; make install
	# cd msh ; make install

clean : 
	cd Make ; make clean
	cd cc ; make install
	cd cp ; make clean
	cd ls ; make clean
	cd pwd ; make clean
	cd rm ; make clean
	cd mknod ; make clean
	cd mkdir ; make clean
	cd echo ; make clean
	cd vi ; make clean
	# cd far ; make clean
	# cd msh ; make clean
