
install : 
	cd Make ; make install
	cd ls ; make install
	cd pwd ; make install
	cd rm ; make install
	cd mknod ; make install

clean : 
	cd Make ; make clean
	cd ls ; make clean
	cd pwd ; make clean
	cd far ; make clean
