#
# cross build for fd2
#
# cmd/fd2/GNUmakefile
#
# The PWB fd2, ported from extra/pwb/spencer/sys/source/s1.  fd2.c
# redirects descriptor 2 and pexec.c is the -lPW path-search routine
# it execs through.  Everything shared is in GNUmakefile.inc.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= fd2
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
