#
# cross build for owner
#
# cmd/owner/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into owner.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= owner
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
