#
# cross build for form
#
# cmd/form/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into form.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= form
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
