#
# cross build for passwd
#
# cmd/passwd/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into passwd.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= passwd
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
