#
# cross build for passwd
#
# cmd/passwd/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into passwd.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= passwd
CLASS	= cmd
#
# Set-user-id root, as the distribution's was: see INSTALLMODE in
# GNUmakefile.inc.
#
MODE	= 4711

include $(DEPTH)/GNUmakefile.inc
