#
# cross build for pr
#
# cmd/pr/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into pr.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= pr
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
