#
# cross build for more
#
# cmd/more/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into more.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= more
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
