#
# cross build for ls
#
# cmd/ls/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into ls.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= ls
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
