#
# cross build for msh
#
# cmd/msh/GNUmakefile
#
# The PWB (Mashey) shell, ported from extra/pwb/spencer.  Everything
# shared is in GNUmakefile.inc: ccc, every .c here, linked into msh.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= msh
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
