#
# Makefile for 
#
# <path>
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

all:

clean:

clobber: clean
OBJECTS= simglb.o sim1.o sim2.o sim3.o sim4.o sim5.o sim6.o sim7.o shim.o
LIB=libz80.a
TARGETS=$(LIB)

$(LIB):	$(OBJECTS)

include ../Makefile.inc


