#
# cross build for dcheck
#
# cmd/dcheck/GNUmakefile
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= dcheck
CLASS	= cmd
LIBS	= $(DEPTH)/lib/fslib/libfs.a

include $(DEPTH)/GNUmakefile.inc
