#
# cross build for chmod
#
# cmd/chmod/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into chmod.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= chmod
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
