#
# cross build for pwbsh
#
# cmd/pwbsh/GNUmakefile
#
# The PWB (Mashey) shell, ported from extra/pwb/spencer.  Everything
# shared is in GNUmakefile.inc: ccc, every .c here, linked into pwbsh.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= pwbsh
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
