#
# cross build for mknod
#
# cmd/mknod/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into mknod.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= mknod
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
