#
# cross build for crypt
#
# cmd/crypt/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into crypt.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= crypt
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
