#
# cross build for ld
#
# cmd/ld/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into ld.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= ld
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
