#
# Makefile for whitesmith random toolchain binaries
#
# cmd/whitesmith/util/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = util
CLASS = cmd/whitesmith

SRCS = $(wildcard *.c)
DOCSRCS = hex.mp  lib.mp  lord.mp  rel.mp

include $(DEPTH)/GNUmakefile.inc
