#
# cross build for cu
#
# cmd/cu/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into cu.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= cu
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
