#
# cross build for ed
#
# cmd/ed/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into ed.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= ed
CLASS	= cmd

#
# e is this same program under a second name, as the native makefile
# has always installed it.
#
ALIAS	= e

include $(DEPTH)/GNUmakefile.inc
