#
# Makefile for 
#
# <path>
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

all:

clean:

clobber: clean
OBJECTS= yaze.o shim.o
TARGETS=libz80.a

$(LIB):	$(OBJECTS)

include ../Makefile.inc
