#
# native Makefile for whitesmiths include files
#
# src/cmd/whitesmith/include
#
# Changed: <2023-07-11 05:39:11 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

INCLUDES = dump.h pascal.h sort.h stdtyp.h utext.h \
	ctype.h math.h pat.h std.h sys.h who.h \
	db.h mount.h sh.h stdio.h time.h

all:
	cp $(INCLUDES) /include

clean:

clobber: clean
