#
# cross build for mkdir
#
# cmd/mkdir/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into mkdir.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= mkdir
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
