:
:	SUBMIT procedure used to create custom .PRL files.
:
:	To use this SUBMIT file type:
:
:	A>SUBMIT MAKEPRL filename
:
:	Where "filename" is the name of your source IBIOS.
:	Thus to follow the example given in IBIOS.DOC you
:	type "SUBMIT MAKEPRL CUSTOM".
:
:	Thió SUBMIÔ filå assumeó thaô thå followinç fileó arå 
:	oî drivå A:
:
:		1) The MAKEPRL.SUB file.
:
:		2) Thå sourcå IBIOÓ filå provideä bù Morro÷ 
:		   Designs and edited by you.
:
:		3) Thå MAÃ assembleò froí Digitaì Research®  
:		   (provideä bù you).
:
:		4) Thå MAKEPRL.COÍ prograí provideä bù Morro÷ 
:		   Designs.
:
era $1.hx?
mac $1 $$pzsz
ren $1.hx0=$1.hex
mac $1 $$+rpzsz
ren $1.hx1=$1.hex
makeprl $1
