#
# cross build for dc
#
# cmd/dc/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into dc.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= dc
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
