#
# libutil - odds and ends shared by the commands
#
# lib/libutil/GNUmakefile
#
# There was no "all" rule here at all, so the tree build stopped dead
# in this directory.  The archive is named libutil.a; libempty.a beside
# it is a checked-in artifact of an older build and is not produced
# here.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= libutil
CLASS	= lib
TARGET	= libutil.a

include $(DEPTH)/GNUmakefile.inc
