#
# cross build for chgrp
#
# cmd/chgrp/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into chgrp.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= chgrp
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
