#
# cross build for cat
#
# cmd/cat/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into cat.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= cat
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
