#
# cross build for kill
#
# cmd/kill/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into kill.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= kill
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
