#
# cross build for find
#
# cmd/find/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into find.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= find
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
