#
# cross build for chown
#
# cmd/chown/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into chown.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= chown
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
