#
# cross build for ln
#
# cmd/ln/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into ln.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= ln
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
