#
# Makefile for updating the source tree
#
# cmd/whitesmith/include/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = include
CLASS = cmd/whitesmith
ROOT = ~/src/micronix/filesystem

SRCS = $(wildcard *.h)

include $(DEPTH)/GNUmakefile.inc
