#
# cross build for cp
#
# cmd/cp/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into cp.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= cp
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
