#
# cross build for less
#
# cmd/less/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into less.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= less
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
