#
# cross build for kstat
#
# cmd/kstat/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into kstat.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= kstat
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
