#
# cross build for packsrc
#
# cmd/packsrc/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into packsrc.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= packsrc
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
