#
# makefile for cc
#
# this upper case Makefile is preferred by the stock make,
# which is why it is so lame
#
# micronix/cmd/cc/Makefile
#
# Changed: <2023-07-12 13:10:34 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

all:	cc

cc : cc.c
	cc -o cc cc.c

clean: ; rm cc *.o

