#
# cross build for tty
#
# cmd/tty/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into tty.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= tty
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
