#
# cross Makefile for asz assemble
#
# usr/src/cmd/asz/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../..
CLASS = cmd
DIR = asz
TARGET = asz
INCFLAG =
LIBS =

include $(DEPTH)/GNUmakefile.inc

test:
	cd tests ; make test
