#
# cross build for s
#
# cmd/s/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into s.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= s
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
