#
# cross build for ps
#
# cmd/ps/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into ps.
#
# This was a stub while ps.c was the recovered 1982 source and did not
# compile against this tree.  It compiles now - the port is in ps.c's
# own header comment - so this is the same four-line GNUmakefile every
# other command in cmd/ has, and "ps" is in DIRS.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= ps
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
