#
# cross build for halt
#
# cmd/halt/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into halt.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= halt
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
