#
# cross build for rm
#
# cmd/rm/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into rm.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= rm
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
