#
# Makefile for updating the source tree
#
# cmd/rm/GNUmakefile
#
# Changed: <2023-07-27 12:11:51 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DIR = rm
CLASS = cmd
ROOT = ~/src/micronix/filesystem
SRCDIR = /usr/src/$(CLASS)/$(DIR)
DEST = $(ROOT)/$(SRCDIR)
NOWARN = --warning=no-ignore-newer

SRCS = $(wildcard *.c *.h)

include ../GNUmakefile.inc
