#
# cross build for wall
#
# cmd/wall/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into wall.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= wall
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
