#
# cross build for cmp
#
# cmd/cmp/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into cmp.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= cmp
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
