#
# Makefile for updating the source tree
#
# cmd/whitesmith/lib/libws/GNUmakefile
#
# Changed: <2023-07-04 19:55:33 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../../..
DIR = libws
CLASS = cmd/whitesmith/lib
ROOT = ~/src/micronix/filesystem
TARGET = libWS.a

include $(DEPTH)/GNUmakefile.inc
