/*
 * mkruleidx - emit the rule table's index, from the rule table.
 *
 * step subscripts ruleidx by a node's root opcode to find where that
 * op's rules begin, and walks them while the op holds.  That works
 * only if the table is sorted by root op with every op in one
 * unbroken run, and only if the index agrees with the table it
 * indexes.
 *
 * Neither can be left to a convention.  A rule filed outside its run
 * is not a rule that misbehaves - it is a rule that is never tried,
 * silently, and the symptom arrives much later as an expression the
 * compiler cannot build.  An index written by hand beside the table
 * is a second copy of what the table says, and the one that used to
 * live here - rulepat - had drifted sixty entries and named a
 * multiply for a program that had none.
 *
 * So this links against the table itself, walks it, refuses to emit
 * anything if the runs are broken, and writes the index out.  The
 * makefile runs it, so a misfiled rule stops the build with a message
 * naming the rule, rather than going quiet until someone writes the
 * expression that needed it.
 */
#include <stdio.h>
#include "pass2.h"
#include "opcodes.h"
#include "rules.h"

#define NOPS	256
#define NORULE	0xffff

int
main(int argc, char **argv)
{
	static unsigned short first[NOPS];
	static unsigned char closed[NOPS];
	unsigned short i, n;
	unsigned char prev;
	int bad = 0;

	for (i = 0; i < NOPS; i++)
		first[i] = NORULE;

	prev = 0;
	for (n = 0; rules[n].op; n++) {
		unsigned char op = rules[n].op;

		if (op != prev) {
			if (closed[op]) {
				fprintf(stderr, "mkruleidx: rules[%u] carries op %u, which had already ended at an\n", (unsigned)n, (unsigned)op);
				fprintf(stderr, "           earlier run.  The table is sorted by root opcode and every\n");
				fprintf(stderr, "           op must be one unbroken run: a rule outside its run is\n");
				fprintf(stderr, "           never tried.  File it with the others of its op.\n");
				bad = 1;
			}
			if (prev)
				closed[prev] = 1;
			prev = op;
		}
		if (first[op] == NORULE)
			first[op] = n;
	}

	if (bad)
		return 1;

	printf("/*\n");
	printf(" * GENERATED by mkruleidx from rules.c - do not edit.\n");
	printf(" *\n");
	printf(" * Where each root opcode's rules begin, or NORULE.  %u rules,\n", (unsigned)n);
	printf(" * checked to be one unbroken run per op when this was made.\n");
	printf(" */\n");
	printf("#include \"pass2.h\"\n");
	printf("#include \"rules.h\"\n\n");
	printf("unsigned short ruleidx[%d] = {", NOPS);
	for (i = 0; i < NOPS; i++) {
		if (i % 8 == 0)
			printf("\n\t");
		if (first[i] == NORULE)
			printf("NORULE, ");
		else
			printf("%5u, ", (unsigned)first[i]);
	}
	printf("\n};\n");
	return 0;
}
