#
# Makefile for updating the source tree
#
# cmd/whitesmith/asm/GNUmakefile
#
# Changed: <2023-07-28 18:57:50 curt>
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH = ../../..
DIR = asm
CLASS = cmd/whitesmith
DOCSRCS = anat.mp dis80.mp as80.mp as80.ic
SRCS = $(wildcard *.c *.h)

include $(DEPTH)/GNUmakefile.inc
