#
# cross build for tail
#
# cmd/tail/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into tail.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= tail
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
