#
# cross build for write
#
# cmd/write/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into write.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= write
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
