#
# cross build for wc
#
# cmd/wc/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into wc.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= wc
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
