#
# this makefile is used only in the crossbuild 
# context.
#
# /GNUmakefile
#
# Changed: <2023-06-26 23:52:23 curt>
#
# the update rule is used when inside the source tree in the simulator
# to sync from the source tree above. currently does nothing.
#
update:

# vim: tabstop=4 shiftwidth=4 noexpandtab:
