#
# this makefile is used to bootstrap the new make
# since the old make prefers the 'Makefile' to 'makefile'
# this one gets read.
#
# /Makefile
#
# Changed: <2023-07-04 10:24:40 curt>

all: /usr/src/cmd/Make/bootstrap 
	sh -v /usr/src/cmd/Make/bootstrap
	/bin/make upgrade

# vim: tabstop=4 shiftwidth=4 noexpandtab:

