#
# this makefile is used to bootstrap the new make
#
# Changed: <2021-12-23 15:51:54 curt>

all : /usr/src/cmd/Make/bootstrap 
	sh -v /usr/src/cmd/Make/bootstrap
	/bin/make upgrade

# vim: tabstop=4 shiftwidth=4 expandtab:

