#
# cross build for tr
#
# cmd/tr/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into tr.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= tr
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
