#
# cross build for djformat
#
# cmd/djformat/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into djformat.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= djformat
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
