#
# cross build for tee
#
# cmd/tee/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into tee.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= tee
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
