#
# cross build for mount
#
# cmd/mount/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into mount.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= mount
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
