/* Auto-generated by mkkw - do not edit */
#include "cpp.h"
#define HI 0x80
#include "lexeme.h"
#define HI 0x80

unsigned char ckw[] = {
	'i'|HI, 8, 'f'|HI, 2, 0xff, IF,
	  'n', 't', 0xff, INT,
	'c'|HI, 27, 'h'|HI, 4, 'a', 'r', 0xff, CHAR,
	  'o'|HI, 14, 'n'|HI, 12, 's'|HI, 3, 't', 0xff, CONST,
	      't', 'i', 'n', 'u', 'e', 0xff, CONTINUE,
	  'a', 's', 'e', 0xff, CASE,
	'r'|HI, 17, 'e'|HI, 15, 't'|HI, 5, 'u', 'r', 'n', 0xff, RETURN,
	    'g', 'i', 's', 't', 'e', 'r', 0xff, REGISTER,
	'f'|HI, 4, 'o', 'r', 0xff, FOR,
	'w'|HI, 6, 'h', 'i', 'l', 'e', 0xff, WHILE,
	'e'|HI, 19, 'l'|HI, 4, 's', 'e', 0xff, ELSE,
	  'n'|HI, 4, 'u', 'm', 0xff, ENUM,
	  'x', 't', 'e', 'r', 'n', 0xff, EXTERN,
	'v'|HI, 15, 'o'|HI, 13, 'i'|HI, 3, 'd', 0xff, VOID,
	    'l', 'a', 't', 'i', 'l', 'e', 0xff, VOLATILE,
	's'|HI, 44, 't'|HI, 13, 'a'|HI, 5, 't', 'i', 'c', 0xff, STATIC,
	    'r', 'u', 'c', 't', 0xff, STRUCT,
	  'i'|HI, 13, 'g'|HI, 5, 'n', 'e', 'd', 0xff, SIGNED,
	    'z', 'e', 'o', 'f', 0xff, SIZEOF_KW,
	  'h'|HI, 5, 'o', 'r', 't', 0xff, SHORT,
	  'w', 'i', 't', 'c', 'h', 0xff, SWITCH,
	'u'|HI, 16, 'n'|HI, 14, 's'|HI, 7, 'i', 'g', 'n', 'e', 'd', 0xff, UNSIGNED,
	    'i', 'o', 'n', 0xff, UNION,
	'l'|HI, 5, 'o', 'n', 'g', 0xff, LONG,
	'b'|HI, 6, 'r', 'e', 'a', 'k', 0xff, BREAK,
	'd'|HI, 12, 'e'|HI, 7, 'f', 'a', 'u', 'l', 't', 0xff, DEFAULT,
	  'o', 0xff, DO,
	'g'|HI, 5, 'o', 't', 'o', 0xff, GOTO,
	't'|HI, 8, 'y', 'p', 'e', 'd', 'e', 'f', 0xff, TYPEDEF,
	'a'|HI, 10, 'u'|HI, 4, 't', 'o', 0xff, AUTO,
	  's', 'm', 0xff, ASM,
	0
};
