OBJS = cc1.o cc2.o cc3.o cc4.o cc5.o cc6.o cc7.o cc8.o cc9.o cutilib.o cdisklib.o

CFLAGS = -Wno-return-type -fdiagnostics-color

qc: $(OBJS)
	cc -o qc $(OBJS)
clean:
	rm -f $(OBJS) qc

cc1.o: cc1.c
cc2.o: cc2.c
cc3.o: cc3.c
cc4.o: cc4.c
cc5.o: cc5.c
cc6.o: cc6.c
cc7.o: cc7.c
cc8.o: cc8.c
cc9.o: cc9.c
cutilib.o: cutilib.c
cdisklib.o: cdisklib.c
