#
# cross build for Make
#
# cmd/Make/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into Make.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= Make
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
