#
# cross build for make
#
# cmd/make/GNUmakefile
#
# This is the make micronix uses.  It was cmd/Make while the v7 make
# still held the name; that one is cmd/v7make now and is not built.
#
# Everything else is in GNUmakefile.inc: ccc from /usr/local, every .c
# in this directory, linked into make.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= make
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
