#
# cross build for ncheck
#
# cmd/ncheck/GNUmakefile
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= ncheck
CLASS	= cmd
LIBS	= $(DEPTH)/lib/fslib/libfs.a

include $(DEPTH)/GNUmakefile.inc
