#
# cross build for cal
#
# cmd/cal/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into cal.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= cal
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
