#
# cross build for sed
#
# cmd/sed/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into sed.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= sed
CLASS	= cmd

include $(DEPTH)/GNUmakefile.inc
