#
# cross build for copy
#
# cmd/copy/GNUmakefile
#
# Everything is in GNUmakefile.inc: ccc from /usr/local, every .c in
# this directory, linked into copy.
#
# BINDIR IS /usr/bin, NOT THE /bin THE REST OF THE COMMANDS GO IN.  The
# distribution kept this with the other text tools - archive, translit
# and the rest - and the native makefile beside this one agrees.
#
# vim: tabstop=4 shiftwidth=4 noexpandtab:

DEPTH	= ../..
DIR	= copy
CLASS	= cmd
BINDIR	= /usr/bin

include $(DEPTH)/GNUmakefile.inc
